<?php
/* ============================================================================
(c) Copyright 2012 Hewlett-Packard Development Company, L.P.
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights to
use, copy, modify, merge,publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================ */
/**
 * @file
 *
 * This file contains the DBaaS Instance class.
 */

namespace HPCloud\Services\DBaaS;

class Instance {

  protected $token;
  protected $projectId;
  protected $url;

  public function __construct($token, $projectId, $endpoint) {
    $this->token = $token;
    $this->projectId = $projectId;
    $this->url = $endpoint;
  }

  public function describe($instanceId) {
  }

  public function listInstances() {
  }

  public function create($name, $flavor = 'medium', $port = NULL, $typeSpec = NULL) {
  }

  public function delete($instanceId) {
  }

  public function restart($instanceId) {
  }

  /**
   * Reset the primary password on this instance.
   *
   * @retval string
   *   The new (autogenerated) password.
   */
  public function resetPassword($instanceId) {
  }


}
